### ISSUE TITLE
Memory map tasks

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#1247]
This is an aggregate covering all of tasks relating to establishing the "load-and-go" memory map which is necessary for compressed ref support.

- [ ] Establish initial heap address space directly after image data segment, adjust `sbrk`
- [ ] Link object files in order by corresponding `type_id` (ascending)
- [ ] Modify `ProgramModule` to declare section order
- [ ] Put ref-typed static fields into a dedicated section
- [ ] Object literal indirection & dedicated section
- [ ] #1245
- [ ] #1242
- [ ] Implement compressed refs
