### ISSUE TITLE
WASM Support

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#1279]
This epic collects the list of tasks necessary in order to add support for WASM.

- [ ] Add a `sysroot` option that is propagated to the C probes
- [x] Parsing of WASM object file format
- [x] Pluggable "probe bundles" which contain predefined probe information
- [x] #1280
- [x] add `WASI` to `org.qbicc.machine.arch.OS` (notice although the OS is WASI, LLVM expects `unknown` in the triplet
- [x] Add support to `emcc` as an alternative toolchain (*)
- [ ] Add support to non-executable binaries (**)
- [x] Cannot arbitrarily use "non-integral" `addrspace(1)`: use addrspace(0) everywhere? [WebAssemblyTypeUtilities.h](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/WebAssembly/Utils/WebAssemblyTypeUtilities.h#L46-L58)
- [x] `common global` crashes llc (SIGILL): use `global`? https://github.com/llvm/llvm-project/issues/55270 
- [ ] Stack maps [may be unsupported for wasm](https://llvm.org/docs/StackMaps.html#supported-architectures). Investigate usage of heap-based shadow stacks.
- [ ] unsupported syscall: `__syscall_mprotect`
- [x] avoid inline assembly (Thread `pause`)
- [x] `Build.Target.isWasm()`

(add more tasks as needed)

**Comment by evacchi** [comment]
memo: ` Build.Target.isWasm()` 

related:
- https://github.com/WebAssembly/wasi-libc/blob/main/tools/wasi-headers/src/c_header.rs#L40-L46
- https://emscripten.org/docs/compiling/Building-Projects.html#detecting-emscripten-in-preprocessor
