### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#1546]
This issue encompasses everything needed to implement our first "real" garbage collector.

- [ ] #1280
- [ ] #1247 (needed to allow all reference-typed values with a fixed locations to be found)
- [x] #1541
- [ ] Introduce safepoint task plugin API
- [ ] Add live value info table to `MethodData` and `StackWalker`
- [ ] Stack walking object marker
- [ ] Static field walking object marker
- [ ] Introduce compacting collector algorithm

Nice to have:

- [ ] #1248 (needed to avoid excessive boot-time relocation of object refs)

**Comment by dgrove-oss** [comment]
A semi-space copying algorithm is typically easier to implement than a mark-compact (fewer moving pieces; simpler invariants).  Consider doing that first?  There will be plenty of bugs to shake out with the root identification and heap tracing support no matter what collection algorithm we build.    In the long run we probably want a generational system with a copying nursery and a mostly non-copying mature space, so the basic copying GC building blocks will still be useful.

**Comment by dmlloyd** [comment]
Sure, that makes sense. I'm far from being an expert on GC algorithms, but I guess a semi-space algorithm would make it easier to track where objects were moved to during the relocation part of the process, compared to compacting which would require an external table.

**Comment by galderz** [comment]
> A semi-space copying algorithm is typically easier to implement than a mark-compact (fewer moving pieces; simpler invariants). Consider doing that first? There will be plenty of bugs to shake out with the root identification and heap tracing support no matter what collection algorithm we build. In the long run we probably want a generational system with a copying nursery and a mostly non-copying mature space, so the basic copying GC building blocks will still be useful.

Btw, GraalVM's serial GC works exactly like that. It uses semi-space copying for both young and old collections.
