### ISSUE TITLE
Additional node types

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#195]
We need the following additional node types added.  Each node type would get a corresponding `BasicBlockBuilder` method (including implementing the method in the `DelegatingBasicBlockBuilder` class), `*Visitor` method(s), a `Copier.Terminus` implementation, and a `SimpleBasicBlockBuilder` implementation.

Update each item with a corresponding issue number if/when the item is to be assigned.  Check off the item when the corresponding issue is closed.

# Value nodes

## Binary operations

- [x] #203 `Cmp`: a `CommutativeBinaryValue` which represents the comparison result of two numbers; has a value of `-1`, `0`, or `1` with a result type of `SignedInteger8`.  Update the handling of `FCMP`, `DCMP`, and `LCMP` in `MethodParser` to emit this node instead of their current behaviors.  Lower to a `compare`/`if` chain.  Add an optimization to the simple optimizer to reduce e.g. `IsGt(Cmp(x, y), 0)` to `IsGt(x, y)` and other variations. Add intrinsics for `(Byte|Short|Integer|Long|Character).compare(Unsigned)?` to emit this node type.
- [x] #206 `Min` and `Max`: `CommutativeBinaryValue`s which represents the minimum/maximum operation for two numbers.  Result type is the input type (both inputs must have the same type).  Introduce intrinsics for `Math.(min|max)`.  Lower to `@llvm.minimum.*` for floating point or `@llvm.(s|u)(min|max)` for all integer types.

## Unary operations

- [x] #680 `Clz` and `Ctz`: `UnaryValue`s which translate to the number of leading or trailing zeros in its integer argument.  LLVM requires the result type to equal the input type; I think this is probably fine.  Add intrinsics for `(Integer|Long).numberOf(Leading|Trailing)Zeros`.  Lower to `@llvm.(ctlz|cttz).*` for all integer types.
- [x] #677 `ByteSwap`: an integer `UnaryValue` whose output equals the input with its bytes swapped. Introduce intrinsics for `(Character|Short|Integer|Long).reverseBytes()`.  Lower to `@llvm.bswap.*` for all integer types.
- [x] #680 `BitReverse`: an integer `UnaryValue` whose output equals the input with its bits fully reversed. Introduce intrinsics for `(Long|Integer).reverse()`.  Lower to `@llvm.bitreverse.*` for all integer types.
- [x] #680 `BitCount`: an integer `UnaryValue` whose output is the number of `1` bits in the input. Introduce intrinsics for `(Integer|Long).bitCount`.  Lower to `@llvm.ctpop.*` for all integer types.
- [ ] #____ `Abs`: a `UnaryValue` whose output equals the absolute value of the input.  Introduce intrinsics for `Math.abs`.  Lower to `@llvm.abs.*` for all integer types and `@llvm.fabs.*` for all floating point types.
- [ ] #205 `Canonical`: a `UnaryValue` which translates its floating point input into its canonical representation according to IEEE 754 "single format" bit layout.  See `Float.floatToIntBits` and `Double.doubleToLongBits` for details.  Intrinsify those methods to use this node followed by a `BitCast`; it should be correct to lower to `@llvm.canonicalize.*` on most if not all supported platforms (but maybe revisit if we ever target i386 with x87 instructions).
- [x] #841 `Comp` ("complement"): a `UnaryValue` whose integer output is of the same type and size as its input, with all bits inverted.  Lower to `xor` with a constant argument.  Optimize `Comp(Comp(x))` to `x` and `Xor(x, x-sized-mask)` to `Comp(x)`.  Also use for inverting boolean expressions.

## Other values

- [ ] #____ `Fma` (fused multiply-add): a `Value` with three same-sized, same-typed inputs whose output is the product of two arguments plus the third argument.  For integer values, lower to a multiply-add sequence (the code generator will recognize and simplify the pattern).  For floating point values, lower to `@llvm.fma.*` (but only if the platform supports it; else keep the implementation of `Math.fma(*)`).  Introduce intrinsics for `Math.fma(*)`.

# Action nodes

- [x] #216 `Fence`: the block builder API exists for this node type but it is unimplemented.  This relates to #152.

# Terminator nodes

- [x] #196 `Unreachable`: a terminator representing an unreachable end of a basic block (for example, after a non-returning function has been called).  Lower to LLVM's `unreachable` instruction.

**Comment by dmlloyd** [comment]
The remaining node types are implementable using LLVM intrinsics for now.  We can revisit if/when we start lowering directly to object files.
