### ISSUE TITLE
Project rename to `qbicc`

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#431]
The QCC project is to be renamed to `qbicc`.  This entails the following work items:

- [x] GitHub organization rename from `quarkuscc` to `qbicc`
- [x] Rename repository `qcc` to `qbicc`
- [x] Rename repository `qcc-class-library` to `qbicc-class-library`
- [x] Register domain `qbicc.org`
- [x] Update actions with renamed repository locations (#443)
- [x] Code freeze
- [x] Maven refactor for group `cc.quarkus` to `org.qbicc` (#448, qbicc/qbicc-class-library#10)
- [x] Maven refactor for artifact prefix `qcc-` to `qbicc-` (#448, qbicc/qbicc-class-library#10)
- [x] Package name migration of `cc.quarkus.qcc` and `cc.quarkus` to `org.qbicc` (#450, qbicc/qbicc-class-library#11)
- [x] Class name migration from `Qcc*`/`QCC*` to `Qbicc*` (#450, qbicc/qbicc-class-library#11)
- [x] Move `ClassContext` from `org.qbicc.type.definition` to `org.qbicc.context` where `CompilationContext` is (#451)
- [x] Rename `ValidatedTypeDefinition*` to `LoadedTypeDefinition*` and `validate()` to `load()` (to wrap up #136) (#451)
- [x] Log category and configuration migration from `cc.quarkus[.qcc]` to `org.qbicc` (#450, qbicc/qbicc-class-library#11)
- [x] Update name in remaining locations (docs, files, etc.) (#450, qbicc/qbicc-class-library#11)

These work items will have to be coordinated among all contributors.  I expect the initial steps to begin on April 1 (no joke!); the contributor-impacting steps (starting with Code freeze) will be coordinated afterwards.
