### ISSUE TITLE
Testing is very difficult without JDK artifacts

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#55]
The only way to currently test QCC is to manually create a `java.base` Maven artifact and install it, which is a significant hurdle to onboarding.

We need JDK artifacts.  A proof-of-something implementation is presented [here](https://github.com/quarkuscc/openjdk-build-script), but this needs to be done better, to meet more requirements:

* Produce an *OS independent* artifact for each JDK module
* Include QCC patch code in each module

Some requisite tasks:

- [x] Establish base project with a Git submodule for the corresponding JDK upstream
- [x] Define Maven modules for each JDK build module
- [x] Supplement or patch the JDK `Makefile`(s) in order to build OS-neutral (Java only) artifacts for each JDK module, which includes all of the platform-specific classes for each module
- [x] Create source directories within each Maven module for classes which are duplicated (with modifications) between each OS (see below) and for patch and native implementation classes
- [x] Create a process whereby the upstream repository can be tracked, such that changes to the upstream repository can be (at least manually, and later maybe partially automatically) applied to the corresponding downstream code

In order to find all source files in OpenJDK which have different variations based on platform, try the following command:

```shell
find `find \`find src -name share -or -name unix -or -name linux -or -name macosx -or -name windows -or -name aix -or -name solaris -or -name posix\` -name classes` -name \*.java -type f -printf '%P\n' | sort | uniq -c | sort -rn
```

*Note: This epic should be transferred to a new repository which will meet these goals, with issues for each subtask.*
