### ISSUE TITLE
Core intrinsics

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#56]
Certain functions will have to become core intrinsics in order to allow the JVM to function at all.  Intrinsics are implemented as a delegating `GraphFactory` implementation which transforms certain method calls.

Note that *only* methods that *cannot* be implemented directly in Java should be made into intrinsics.

- [x] Introduce intrinsics plugin, which includes the `GraphFactory` implementation along with an efficient registry (intrinsic lookup should be an O(1) operation)
- [x] `Thread.currentThread()` should translate to a special `Value`, which will ultimately be read from an implicit parameter of every Java method
- [x] `java.lang.Class#cast`
- [x] `java.lang.Class#isArray`
- [x] `java.lang.Class#isAssignableFrom`
- [x] `java.lang.Class#isInstance`
- [x] `java.lang.Class#isInterface`
- [x] `java.lang.Class#isPrimitive`
- [x] `java.lang.Object#clone` - custom `Value` probably
- [x] `java.lang.Object#getClass` - could be native code?
- [x] `java.lang.Object#hashCode` - could be native code?
- [x] `java.lang.Throwable#fillInStackTrace`
- [x] The operations within `cc.quarkus.api.Values` should be mapped to their corresponding `Value` implementations
- [ ] The operations in `cc.quarkus.api.Tuning` should be implemented to modify the likelihood of their corresponding operations
- [ ] `cc.quarkus.c_native.api.Pin` should be implemented by way of special `Value`s and memory operations (todo: see if this can be done via the native API instead)

Add more *required* intrinsics here.  Do not add things that should be implemented using `c_native`, or things which are intrinsics for optimization reasons.  Most `Unsafe` methods should be implemented in Java to relay to `Values` or use `c_native` directly.

**Comment by dmlloyd** [comment]
These (and more) are done!
