### ISSUE TITLE
Local variable support

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#578]
Introduce support for local variables.  This comes with several pieces.

- [x] Introduce local variable elements
- [x] Introduce value handles for local variables
- [ ] Create local variable elements corresponding to the frame state table in each method (based on slot and type combination)
- [ ] Use load and store operations to populate local variables
- [ ] Introduce LLVM lowering for allocation of variable values at scope-appropriate times
- [ ] Introduce LLVM lowering for loading and storing variable values
- [ ] Map variable debugging information to actual variables
- [ ] Establish "lexical scopes" for variables that are compatible with DWARF
- [ ] Introduce LLVM lowering for local variable debug information
