### ISSUE TITLE
Code correctness (core) plugin

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#58]
There are several correctness transformations that are intended to be employed by a core plugin, in order to keep the bytecode parser as simple as possible.  These transformations correspond to detection of run-time problems that would otherwise cause undefined behavior (UB) on the back end or a crash.  We need a code correctness plugin which performs the following tasks:

- [x] Automatic narrowing/widening/value cast/bitcast where type mismatches occur in operations
- [x] Null checking of dereferences for methods, fields, and array accesses
- [x] Zero divisor checking for integer divisions
- [x] Range checking for array accesses
- [x] Detect incompatible class changes (static invocation of instance method and vice-versa, etc) and replace such calls with `IncompatibleClassChangeError` throw
- [x] Consider moving the validation logic around `checkcast` and `instanceof` out of the core bytecode parser and into this plugin
- [x] Shift distance masking to 32 or 64 (`and` with `0x1f` or `0x3f`) (`*shl`,`*shr`,`*ushr`)
- [x] Range checks (saturation) for fp-to-integer conversions where the result is out of the range of the target type
- [ ] Auto-boxing/unboxing of arguments to methods, values being stored in fields and arrays, values being read from fields and arrays

Additional tasks should only be as required; in particular, optimizations should be excluded from this plugin (at least for now) and implemented separately.
