### ISSUE TITLE
Fixing pointer dereferencing problems

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#695]
Pointer dereferencing has a few problems that must be addressed (no pun intended).  In order for the Java level constructs to all work properly, the various eager `load` ops need to be eliminated from C-style element/member access chains.

Here are the steps:

- [x] #712
- [x] #754
- [x] #752
- [x] Ensure that field accesses to pointer-to-structure types translate e.g. `foo.bar` to `AddressOf(MemberOf(PointerHandle(<foo>), <bar>))`
- [x] Ensure that array element accesses to pointer types translate e.g. `foo[123]` to `AddressOf(ElementOf(PointerHandle(<foo>), 123))`
- [x] Fix `CNative.ptr#get()` to work identically to array element accesses (i.e. return the address of the element rather than the element itself)
- [x] Eliminate redundant loads used by `addr_of` and other similar constructs (a useless load elimination pass could suffice, however if the field happens to be `volatile` or something then such a pass would not be able to eliminate the load unless it knew for sure that it was only used for this purpose)
- [x] Ensure that the existing optimization of `PointerHandle(AddressOf(X)) -> X` still holds for above, so that e.g. `foo[123].bar` becomes `AddressOf(MemberOf(ElementOf(PointerHandle(<foo>), 123), <bar>))`

** If automatic promotion doesn't work out (due to too many ambiguities or something like that) then we'll have to explore another strategy, like introducing a new `Deref(ValueHandle)` node which represents a *possible* load and go from there.

**Comment by dmlloyd** [comment]
> @dmlloyd what did you mean by CNative.load? That doesn't currently exist.

Sorry that was an error, I was referring to `CNative.ptr#get(*)`.

**Comment by theresa-m** [comment]
Update from https://github.com/qbicc/qbicc/pull/772#pullrequestreview-810132283:

> We might have to pivot to a completely different approach, like abandoning Deref and transforming either or both of:
> 
> Load(MemberOf(Load(MemberOf(x, m1), NONE), m2), NONE) -> Load(MemberOf(MemberOf(x, m1), m2), NONE)
> ExtractMember(Load(x, NONE), m1) -> Load(MemberOf(x, m1), NONE) (this one is slightly complicated by the fact that the new load has to be placed with the original load due to ordering, which requires coordination between two phases: one to discover the member extraction and one to generate the load)
> ...and then sweeping up the unused whole-structure loads using a new load elimination pass. (Also apply similar transformations to array value nodes.)

**Comment by dmlloyd** [comment]
This is essentially complete. There may be some lingering bugs but I think the basic behaviors are verified.
