### ISSUE TITLE
Clean up all remaining uses of `MemoryAtomicityMode`

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc#948]
Clean up usages of `MemoryAtomicityMode`, with a maximum of one module per PR to reduce the window for merge conflicts.  Replace usages according to this table:

* `NONE` -> `SingleUnshared`
* `UNORDERED` -> no mode (default `load`/`store` methods) or `SinglePlain` if one must be given
* `MONOTONIC` -> `SingleOpaque`
* `ACQUIRE`, `RELEASE`, `ACQUIRE_RELEASE`, `SEQUENTIALLY_CONSISTENT`, and `VOLATILE` -> depends on usage; in most cases, there should be a JMM reference describing the specific expected semantics; mostly it will be a combination of:
    * `SinglePlain`
    * `GlobalAcquire`
    * `GlobalRelease`
    * `GlobalSeqCst`

Clean up in the following modules (tear off to take a subtask):
* [x] #968
* [x] #960
* [x] #956
* [x] Clean up `MemoryAtomicityMode`: module `qbicc-plugin-core-classes`
* [x] Clean up `MemoryAtomicityMode`: module `qbicc-plugin-correctness`
* [x] #958
* [x] #955
* [x] #964
* [x] #967
* [x] Clean up `MemoryAtomicityMode`: module `qbicc-plugin-lowering`
* [x] #953
* [x] #954
* [x] Clean up `MemoryAtomicityMode`: module `qbicc-plugin-thread-local`

And then remove the class altogether.
